# Generated by Django 4.0 on 2023-11-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
